- name: yum install bacepackage
  yum: name={{ item }} state=present
  loop:
    - vim
    - zsh
    - git
    - tree
    # - htop エラー文：No package matching 'htop' found available, installed or updated
    # - iftop エラー文：No package matching 'iftop' found available, installed or updated
    - mlocate
    - telnet
    - wget
    - ipa-pgothic-fonts

- name: stop firewalld
  systemd: name=firewalld enabled=no state=stopped
