- name: copy nginx.repo
  copy:
    src: "{{ item.src }}"
    dest: "/etc/yum.repos.d/{{ item.dest }}"
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/nginx/files/nginx.repo, dest: . }

- name: install nginx
  yum: name={{ item }} state=present
  loop:
  - nginx

- name: start nginx
  systemd: name=nginx enabled=yes state=started

- file: path=/var/www/{{ item.name }} state=directory owner=root group=root mode=0755
  loop:
    - { name: 'wordpress' }

- name: copy nginx conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/nginx/files/conf.d, dest: . }
  notify: restart nginx
